// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiRBTTej7w3n4EyxuEp5GNkZT_M9dBdXo',
    appId: '1:1041994959023:web:ae05fb602afd7025682c5a',
    messagingSenderId: '1041994959023',
    projectId: 'gifedit-24349',
    authDomain: 'gifedit-24349.firebaseapp.com',
    storageBucket: 'gifedit-24349.firebasestorage.app',
    measurementId: 'G-3GJ3KHTPDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWWslida68p09fAxoLVOIujSUEyS80iI',
    appId: '1:1041994959023:android:de8ee0d2a068138d682c5a',
    messagingSenderId: '1041994959023',
    projectId: 'gifedit-24349',
    storageBucket: 'gifedit-24349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvHCBq29HJ6uYvy34EjtzuA1JG4L0AjQ',
    appId: '1:1041994959023:ios:2ed0f621f3fb1bbd682c5a',
    messagingSenderId: '1041994959023',
    projectId: 'gifedit-24349',
    storageBucket: 'gifedit-24349.firebasestorage.app',
    iosBundleId: 'com.example.memecreat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvHCBq29HJ6uYvy34EjtzuA1JG4L0AjQ',
    appId: '1:1041994959023:ios:2ed0f621f3fb1bbd682c5a',
    messagingSenderId: '1041994959023',
    projectId: 'gifedit-24349',
    storageBucket: 'gifedit-24349.firebasestorage.app',
    iosBundleId: 'com.example.memecreat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiRBTTej7w3n4EyxuEp5GNkZT_M9dBdXo',
    appId: '1:1041994959023:web:6641bf071cd5a70e682c5a',
    messagingSenderId: '1041994959023',
    projectId: 'gifedit-24349',
    authDomain: 'gifedit-24349.firebaseapp.com',
    storageBucket: 'gifedit-24349.firebasestorage.app',
    measurementId: 'G-5JJS0NCKZB',
  );
}
